import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type F = { children: any }

export default function RootLayout({ children }: F) {
  return (
    <html lang="en">
      <body className=
        {inter.className}
      >
        {children}
      </body>
    </html>
  )
}
