'use client';

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import toast, { Toaster } from 'react-hot-toast';
import { ReactQueryProvider } from './ReactQueryprovider'
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import MuiProvider from './mui-provider';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { Providers } from "./providers";



// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'LOG IN',
//   description: 'Generated by create next app',
// }

type F = { children: any }

export default function RootLayout({ children }: F) {
  return (
    <html lang="en">
      <body className='bg-slate-300 w-screen h-screen flex justify-center items-center flex-wrap p-[40px]'>
      <Providers>
        <MuiProvider>
          <ReactQueryProvider>
            {children}

            <Toaster />
            <ReactQueryDevtools />
          </ReactQueryProvider>
        </MuiProvider>
        </Providers>
      </body>
    </html>
  )
}
