'use client';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import toast, { Toaster } from 'react-hot-toast';
import { ReactQueryProvider } from './ReactQueryprovider'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'LOG IN',
//   description: 'Generated by create next app',
// }

type F = { children: any }

export default function RootLayout({ children }: F) {
  return (
    <html lang="en">
      <body className='bg-gradient-to-r from-red-400 to-yellow-300 w-screen h-screen flex justify-center items-center '>
        <ReactQueryProvider>
          {children}
          <Toaster />
        </ReactQueryProvider>
      </body>
    </html>
  )
}
